services:
  redis:
    image: registry.lil.tools/library/redis:6.0.11
  web:
    image: registry.lil.tools/harvardlil/caching-test:0.01
    volumes:
      - .:/app
    depends_on:
      - redis
    tty: true
    stdin_open: true
